//! SeaORM Entity. Generated by sea-orm-codegen 0.4.2

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel)]
#[sea_orm(table_name = "labels")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: String,
    pub name: String,
    pub created_at: DateTimeWithTimeZone,
    pub updated_at: Option<DateTimeWithTimeZone>,
    pub device_id: String,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::devices::Entity",
        from = "Column::DeviceId",
        to = "super::devices::Column::Id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    Devices,
}

impl Related<super::devices::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Devices.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}

use chrono::{DateTime, Local};
use poem_openapi::Object;
#[derive(Debug, Object, Clone, Eq, PartialEq)]
pub struct LabelResp {
    /// 设备ID
    pub id: String,
    /// 设备名称
    pub name: String,
    /// 设备创建时间
    pub created_at: DateTime<Local>,
}
impl From<Model> for LabelResp {
    fn from(obj: Model) -> Self {
        LabelResp {
            id: obj.id,
            name: obj.name,
            created_at: obj.created_at.into(),
        }
    }
}
