//! SeaORM Entity. Generated by sea-orm-codegen 0.6.0

use poem_openapi::Enum;
use sea_orm::entity::prelude::*;

#[derive(EnumIter, DeriveActiveEnum, Clone, Debug, Eq, PartialEq, Enum)]
#[sea_orm(rs_type = "String", db_type = "Enum", enum_name = "data_type")]
pub enum DataType {
    #[sea_orm(string_value = "string")]
    String,
    #[sea_orm(string_value = "number")]
    Number,
    #[sea_orm(string_value = "integer")]
    Integer,
    #[sea_orm(string_value = "boolean")]
    Boolean,
    #[sea_orm(string_value = "time")]
    Time,
}
